### ISSUE TITLE
Works Well

### ISSUE THREAD

**Issue by Mr-Anonymous** [kamilkp/autoheight#1]
Hi kamilkp,

this is not an issue but rather a comment to say that this autogrow Angular directive works really well. I have tried other angular directives but the problem I had with them all was autogrow doesnt work when the model is updated dynamically via $http. But your directive works perfect. 

Thanks for sharing this. :)

Cheers,
Neel.

**Comment by lakartoza** [comment]
Nice to hear that Neel. I also want to use because I update my model dynamically with $http but I'm having trouble getting it started. All you do is include the angular-autogrow.js file and add the autoheight attribute to the textarea. Correct?

**Comment by Mr-Anonymous** [comment]
Hi @lakartoza , Yes. I did the following to get it to work:

1) I include the `angular-autoheight.js` file 
2) I add the `autoheight` module dependancy and
3) Added the `autoheight` directive to the textarea.
